"""the run record

Revision ID: 9eb7f485ecad
Revises:
Create Date: 2026-08-31 16:13:27.289594

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9eb7f485ecad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abstractions",
        sa.Column("abstraction_id", sa.String(), nullable=False),
        sa.Column("config_hash", sa.String(), nullable=False),
        sa.Column(
            "shape", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "built_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("abstraction_id"),
    )
    op.create_table(
        "legs",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("leg", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("task_id", "attempt", "leg"),
    )
    op.create_index("legs_leg_at", "legs", ["leg", sa.literal_column("at DESC")], unique=False)
    op.create_index(
        "legs_run", "legs", ["run_id"], unique=False, postgresql_where=sa.text("run_id IS NOT NULL")
    )
    op.create_table(
        "progress",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("subject_id", sa.String(), nullable=False),
        sa.Column("op", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("base", sa.BigInteger(), nullable=True),
        sa.Column("done", sa.BigInteger(), nullable=True),
        sa.Column("total", sa.BigInteger(), nullable=True),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("window_seconds", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("scope", "subject_id", "op"),
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("config_name", sa.String(), nullable=False),
        sa.Column("kernel", sa.String(), nullable=True),
        sa.Column("arm", sa.String(), nullable=True),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("parent_run_id", sa.String(), nullable=True),
        sa.Column("action_config_hash", sa.String(), nullable=True),
        sa.Column("card_abstraction_hash", sa.String(), nullable=True),
        sa.Column("config_hash", sa.String(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("git_commit", sa.String(), nullable=True),
        sa.Column("git_dirty", sa.Boolean(), nullable=True),
        sa.Column("git_branch", sa.String(), nullable=True),
        sa.Column("code_snapshot", sa.String(), nullable=True),
        sa.Column("storage_capacity", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), server_default="running", nullable=False),
        sa.Column("iterations", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("num_infosets", sa.BigInteger(), nullable=True),
        sa.Column("runtime_seconds", sa.Float(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        "runs_experiment",
        "runs",
        ["experiment_id"],
        unique=False,
        postgresql_where=sa.text("experiment_id IS NOT NULL"),
    )
    op.create_index("runs_listing", "runs", [sa.literal_column("started_at DESC")], unique=False)
    op.create_table(
        "checkpoints",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("iteration", sa.BigInteger(), nullable=False),
        sa.Column("blob_uri", sa.String(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=True),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("abstraction_id", sa.String(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "written_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "iteration"),
    )
    op.create_index(
        "checkpoints_current",
        "checkpoints",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "evals",
        sa.Column("eval_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("checkpoint_iteration", sa.BigInteger(), nullable=True),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("base_seed", sa.Integer(), nullable=True),
        sa.Column(
            "knobs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("tier_digest", sa.String(), nullable=False),
        sa.Column("exploitability_mbb", sa.Float(), nullable=True),
        sa.Column("std_error_mbb", sa.Float(), nullable=True),
        sa.Column("num_hands", sa.BigInteger(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("eval_id"),
    )
    op.create_index(
        "evals_pairing", "evals", ["tier_digest", "run_id", "checkpoint_iteration"], unique=False
    )
    op.create_index("evals_run", "evals", ["run_id", "checkpoint_iteration"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("gseq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "iteration",
            sa.BigInteger(),
            sa.Computed("(body->>'iteration')::bigint", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("gseq"),
    )
    op.create_index("run_events_fold", "run_events", ["run_id", "attempt", "gseq"], unique=False)
    op.create_index(
        "run_events_iter",
        "run_events",
        ["run_id", "iteration"],
        unique=False,
        postgresql_where=sa.text("iteration IS NOT NULL"),
    )
    op.create_index(
        "run_events_kind",
        "run_events",
        ["run_id", "event", sa.literal_column("gseq DESC")],
        unique=False,
    )
    op.create_index("run_events_replay", "run_events", ["event_uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("run_events_replay", table_name="run_events")
    op.drop_index("run_events_kind", table_name="run_events")
    op.drop_index(
        "run_events_iter",
        table_name="run_events",
        postgresql_where=sa.text("iteration IS NOT NULL"),
    )
    op.drop_index("run_events_fold", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("evals_run", table_name="evals")
    op.drop_index("evals_pairing", table_name="evals")
    op.drop_table("evals")
    op.drop_index(
        "checkpoints_current", table_name="checkpoints", postgresql_where=sa.text("is_current")
    )
    op.drop_table("checkpoints")
    op.drop_index("runs_listing", table_name="runs")
    op.drop_index(
        "runs_experiment", table_name="runs", postgresql_where=sa.text("experiment_id IS NOT NULL")
    )
    op.drop_table("runs")
    op.drop_table("progress")
    op.drop_index("legs_run", table_name="legs", postgresql_where=sa.text("run_id IS NOT NULL"))
    op.drop_index("legs_leg_at", table_name="legs")
    op.drop_table("legs")
    op.drop_table("abstractions")
    # ### end Alembic commands ###
