"""The payload fixture the console's schemas are checked against.

Nothing else connects Python's dicts to TypeScript's expectations. `PAYLOADS`
already pins every command's shape here, so exporting it gives the console a
contract to test against that is not invented and cannot quietly drift: a
Python-side change fails THIS test, which forces the fixture to change, which
fails the TypeScript one by name.

Generated rather than hand-written for the same reason -- a hand-copied fixture
is a second declaration, and this whole seam exists to avoid those.
"""

from __future__ import annotations

import json
from pathlib import Path

from tests.interfaces.cli.test_command_renderers import PAYLOADS

FIXTURE = Path(__file__).resolve().parents[3] / "console" / "src" / "api" / "payloads.fixture.json"

BANNER = "GENERATED by tests/interfaces/cli/test_payload_fixture.py -- do not edit"


def _serialise() -> str:
    return json.dumps({"_": BANNER, **PAYLOADS}, indent=2, sort_keys=True, default=str) + "\n"


def test_the_fixture_matches_the_payloads(request: object) -> None:
    """Regenerate on mismatch, and fail -- so the diff is reviewed, not absorbed.

    Writing it silently would let a payload change reach the console without
    anyone seeing that the contract moved.
    """
    expected = _serialise()
    if not FIXTURE.exists() or FIXTURE.read_text() != expected:
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(expected)
        raise AssertionError(
            f"{FIXTURE.name} was stale and has been regenerated. Review the diff: the "
            "console's Zod schemas are checked against it, so a change here is a change "
            "to the contract the UI reads."
        )


def test_every_command_is_in_the_fixture() -> None:
    """The fixture is only a contract if it covers everything."""
    from src.interfaces.cli.commands import COMMANDS

    assert set(PAYLOADS) == {command.name for command in COMMANDS}
