-- 0001_initial.sql -- the run record as relational tables.
--
-- Numbered and FORWARD-ONLY. Applied in order; `schema_migrations` records what
-- has run. Hand-written rather than autogenerated on purpose: a dispatch seals
-- its code snapshot and runs 24-36 h, so a node is routinely writing week-old
-- code against this schema. That makes every migration additive-only while
-- anything is in flight, and additive-only is a REVIEW discipline -- an
-- autogenerated diff is a thing you approve, not a thing you read.
--
-- Every departure from the first draft of this schema is a defect one of four
-- reviews found against the code. The comments say which; the reason is the
-- part that rots.

-- ---------------------------------------------------------------------------
-- runs
-- ---------------------------------------------------------------------------
-- Columns, not jsonb, for everything a LISTING filters or groups on: a listing
-- is the only place the set of experiments exists, and an arm is uninterpretable
-- without its control.
CREATE TABLE runs (
    run_id               text PRIMARY KEY,
    config_name          text NOT NULL,
    kernel               text,
    arm                  text,
    experiment_id        text,
    parent_run_id        text,

    -- Lineage discriminators. Copied onto every eval row, and a NULL
    -- card_abstraction_hash is what `runinfo` reports as a provenance gap.
    action_config_hash   text,
    card_abstraction_hash text,
    config_hash          text,

    -- `verify_trainer_knobs` compares whole config blocks by EQUALITY, so this
    -- is stored losslessly rather than summarised. It is also the payload a
    -- resume needs and that a blob listing can never reconstruct.
    config               jsonb NOT NULL,

    git_commit           text,
    git_dirty            boolean,
    git_branch           text,   -- a commit does not identify an ARM here
    code_snapshot        text,

    storage_capacity     bigint,
    started_at           timestamptz NOT NULL,
    completed_at         timestamptz,

    -- Folded from events, cached here for the listing. `running` is the safe
    -- default: a sweeper that reads absence as terminal deletes a live ladder.
    status               text NOT NULL DEFAULT 'running',
    iterations           bigint NOT NULL DEFAULT 0,
    num_infosets         bigint,
    runtime_seconds      double precision NOT NULL DEFAULT 0
);
CREATE INDEX runs_experiment ON runs (experiment_id) WHERE experiment_id IS NOT NULL;
CREATE INDEX runs_listing    ON runs (started_at DESC);

-- ---------------------------------------------------------------------------
-- run_events
-- ---------------------------------------------------------------------------
-- `seq` was TWO JOBS IN ONE COLUMN in the first draft: a per-run identity for
-- replay, and a global cursor for the SSE stream. They cannot be the same
-- column, which the spike proved by needing a second one before the cursor
-- query could be written at all.
CREATE TABLE run_events (
    -- Server-assigned. THE global ordering, and the only thing the cursor reads.
    gseq        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    run_id      text NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    -- Which attempt emitted it. Load-bearing: the run-vs-attempt `status`
    -- scoping exists because an unscoped fold read two live runs as `died`.
    attempt     integer NOT NULL DEFAULT 0,
    event       text NOT NULL,   -- created|attempt_started|attempt_ended|
    at          timestamptz NOT NULL,  --   progress|checkpoint|status
    body        jsonb NOT NULL,

    -- Client-assigned, and ONLY for idempotent replay. Two processes write one
    -- run's events -- the node wrapper and the trainer subprocess -- so a
    -- client-computed monotone `seq` would collide, and the sink would swallow
    -- the rejection. A uuid does not collide.
    event_uuid  uuid NOT NULL,

    iteration   bigint GENERATED ALWAYS AS ((body->>'iteration')::bigint) STORED
);
-- Replay is a no-op rather than a duplicate, and cannot deadlock two producers.
CREATE UNIQUE INDEX run_events_replay ON run_events (event_uuid);
CREATE INDEX run_events_fold  ON run_events (run_id, attempt, gseq);
CREATE INDEX run_events_kind  ON run_events (run_id, event, gseq DESC);
CREATE INDEX run_events_iter  ON run_events (run_id, iteration) WHERE iteration IS NOT NULL;

-- ---------------------------------------------------------------------------
-- checkpoints  -- A DERIVED CACHE. Never a claim.
-- ---------------------------------------------------------------------------
-- The first draft had `complete boolean`, which put the advertisement in
-- Postgres and the bytes in Blob: two systems that can disagree, and one
-- disagreement is exactly the state `require_complete` exists to refuse.
--
-- One rung is now ONE blob, committed atomically, so BLOB EXISTENCE IS
-- COMPLETENESS and every row here is rebuildable from one prefix listing.
CREATE TABLE checkpoints (
    run_id        text NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    iteration     bigint NOT NULL,
    blob_uri      text NOT NULL,
    bytes         bigint,

    -- WITHOUT THESE TWO, TWO GUARDS GO UN-ARMED. A wrong-tree or rebucketed
    -- load does not fail -- it silently reinterprets every row as a different
    -- infoset and continues training on scrambled regrets.
    fingerprint   text NOT NULL,
    abstraction_id text,

    -- The manifest distinguished the CURRENT snapshot from retained rungs, and
    -- loads resolve through that distinction.
    is_current    boolean NOT NULL DEFAULT false,
    written_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, iteration)
);
CREATE UNIQUE INDEX checkpoints_current ON checkpoints (run_id) WHERE is_current;

-- ---------------------------------------------------------------------------
-- evals
-- ---------------------------------------------------------------------------
-- THE CORRECTION THAT MATTERS MOST. The first draft had a `tier` column and
-- paired on five fields. `tier` is an ORDINAL INTO A QUERY RESULT -- `--tier 0`
-- means "position 0 in a ranked list" and renumbers when a row is added -- so
-- as a column it is either meaningless or changes on insert.
--
-- The real pairing key is ~30 knobs: two identity hashes, three unconditional
-- knobs and 24 conditional ones, including `policy_threshold` and `avg_gamma`
-- (worth ~80 and ~105 mbb) and the BR tier widths. Pairing on five fields would
-- have silently compared incomparable rows.
CREATE TABLE evals (
    eval_id              text PRIMARY KEY,
    run_id               text NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,

    -- A real column: it is the curve's x-axis, and a row without one is
    -- unplaceable rather than merely incomplete. NULL is a real value.
    checkpoint_iteration bigint,

    method               text NOT NULL,
    -- `base_seed`, NOT `board_seed`: exact_br mirrors board_seed into base_seed,
    -- and a column named board_seed matches no row ever written.
    base_seed            integer,

    -- Source of truth for the tier. Conditional knobs are written ONLY when
    -- non-default and compared ONLY when present on one side, so promoting them
    -- to NOT NULL DEFAULT false would collapse absent into explicit-false and
    -- re-pair every legacy row. They stay here, three-valued.
    knobs                jsonb NOT NULL DEFAULT '{}',

    -- Computed in PYTHON by the same `tier_key` code path, never re-derived in
    -- SQL: a second implementation of the pairing rule is a second thing to
    -- drift. This column exists so the index can be built on it.
    tier_digest          text NOT NULL,

    exploitability_mbb   double precision,
    std_error_mbb        double precision,
    num_hands            bigint,          -- a pairing PRECONDITION, not a stat
    recorded_at          timestamptz NOT NULL,
    payload              jsonb NOT NULL DEFAULT '{}'   -- incl. pair_samples_mbb
);
-- The pairing key, encoded so the mistake is harder to make than to avoid.
CREATE INDEX evals_pairing ON evals (tier_digest, run_id, checkpoint_iteration);
CREATE INDEX evals_run     ON evals (run_id, checkpoint_iteration);

-- ---------------------------------------------------------------------------
-- legs  -- the task record, INCLUDING the observer half
-- ---------------------------------------------------------------------------
-- `observed` was missing from the first draft. It is the BATCH half of the
-- join -- the only account of a death the node did not survive -- and without
-- it every OOM-kill and node-loss stays unresolved forever, which cascades into
-- `cost` (dropped as unended), `runinfo` and `tasks` re-asking Batch on every
-- poll. It is also the one leg written by the READER, not the node.
CREATE TABLE legs (
    task_id   text NOT NULL,
    -- A Batch retry REUSES the task id, so the natural key includes the attempt.
    attempt   integer NOT NULL DEFAULT 0,
    leg       text NOT NULL,   -- start|exit|observed|progress|bundle
    run_id    text,
    at        timestamptz NOT NULL,
    body      jsonb NOT NULL,
    PRIMARY KEY (task_id, attempt, leg)
);
CREATE INDEX legs_run    ON legs (run_id) WHERE run_id IS NOT NULL;
-- The spike found this one: 7.45ms on a seq scan, 1.59ms with it.
CREATE INDEX legs_leg_at ON legs (leg, at DESC);

-- NOTE: `cause` and `cause_source` are deliberately NOT columns here. They are
-- derived at READ time from (exit.cause, observed.state) by one precedence
-- rule; materialising them freezes that rule into whichever writer ran first.

-- ---------------------------------------------------------------------------
-- progress  -- four artifacts, three key shapes
-- ---------------------------------------------------------------------------
-- `train-progress` is per run, `evaluate-progress` per run dir, `legs/*.progress`
-- per TASK (not per attempt -- it goes stale rather than absent), and
-- `precompute-progress` is per ABSTRACTION and has no run_id at all. One table
-- needs an explicit scope rather than a run_id column that is sometimes a lie.
CREATE TABLE progress (
    scope          text NOT NULL,   -- 'run' | 'task' | 'abstraction'
    subject_id     text NOT NULL,
    op             text NOT NULL,
    unit           text,
    base           bigint,
    done           bigint,
    total          bigint,
    rate           double precision,
    -- Without it the ETA is a guess: `remaining` uses the measured window.
    window_seconds double precision,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (scope, subject_id, op)
);

-- ---------------------------------------------------------------------------
-- abstractions  -- the table the first draft had no key for
-- ---------------------------------------------------------------------------
-- `metadata.json` and `precompute-progress.json` are keyed by ABSTRACTION, not
-- by run. A run-centric schema simply had nowhere to put them, and the resolver
-- raises rather than resolve past this file because doing so would drop the
-- config_hash a checkpoint is pinned to.
CREATE TABLE abstractions (
    abstraction_id text PRIMARY KEY,
    config_hash    text NOT NULL,
    shape          jsonb NOT NULL DEFAULT '{}',   -- per-street bucket counts
    built_at       timestamptz NOT NULL DEFAULT now()
);
